# Generated by Django 5.0.3 on 2025-09-25 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_finall',
            new_name='is_finaly',
        ),
    ]
