# Generated by Django 5.0.3 on 2025-09-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_is_finall_order_is_finaly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تخفیف روی فاکتور'),
        ),
    ]
