# Generated by Django 5.0.3 on 2025-09-29 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_paymenttype_order_description_order_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_state_title', models.CharField(max_length=50, verbose_name='وضعیت سفارش')),
            ],
            options={
                'verbose_name': 'وضعیت سفارش',
                'verbose_name_plural': 'انواع وضعیتهای سفارش',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_states', to='orders.orderstate', verbose_name='وضعیت سفارش'),
        ),
    ]
