# Generated by Django 5.1.3 on 2025-03-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='family',
            field=models.CharField(blank=True, max_length=50, verbose_name='نام خانوادگی'),
        ),
    ]
